[package]
name = "test-fuzz"
version = "0.1.0-alpha.10"
edition = "2018"

description = "To make fuzzing Rust easy"

authors = ["Samuel E. Moelius III <sam@moeli.us>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/smoelius/test-fuzz"

[dependencies]
afl = "=0.10.0"
serde = "1.0"

runtime = { path = "./runtime", package = "test-fuzz-runtime", version = "=0.1.0-alpha.10" }
test-fuzz-macro = { path = "./macro", version = "=0.1.0-alpha.10" }

[dev-dependencies]
assert_cmd = "1.0.2"
cargo_metadata = "0.12.3"
dirs = { path = "./dirs", package = "test-fuzz-dirs", version = "=0.1.0-alpha.10" }
lazy_static = "1.4.0"
semver = "0.11.0"

[features]
default = []
logging = ["test-fuzz-macro/logging"]
persistent = ["test-fuzz-macro/persistent"]

[workspace]
members = [
    "cargo-test-fuzz",
    "dirs",
    "examples",
    "macro",
    "runtime",
]
