[package]
name = "test-fuzz"
version = "0.1.0-alpha.4"
edition = "2018"

description = "To make fuzzing Rust easy"

authors = ["Samuel E. Moelius III <sam@moeli.us>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/smoelius/test-fuzz"

[dependencies]
afl = "0.8.0"

dirs = { path = "./dirs", package = "test-fuzz-dirs", version = "0.1.0-alpha" }
runtime = { path = "./runtime", package = "test-fuzz-runtime", version = "0.1.0-alpha" }
test-fuzz-macro = { path = "./macro", version = "0.1.0-alpha" }

[features]
default = []
logging = ["test-fuzz-macro/logging"]
persistent = ["test-fuzz-macro/persistent"]
