[package]
name = "test-fuzz-macro"
version = "0.1.0-alpha.9"
edition = "2018"

description = "test-fuzz-macro"

authors = ["Samuel E. Moelius III <sam@moeli.us>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/smoelius/test-fuzz"

[lib]
proc-macro = true

[dependencies]
darling = "0.12.0"
proc-macro2 = "1.0.24"
quote = "1.0.8"
syn = { version = "1.0.60", features = ["full", "visit-mut"] }
unzip-n = "0.1.2"

[features]
logging = []
persistent = []
