[package]
name = "test-fuzz-macro"
version = "0.1.0-alpha"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.10.2"
proc-macro2 = "1.0.19"
quote = "1.0.7"
syn = "1.0.39"
unzip3 = "1.0.0"

[features]
logging = []
persistent = []
