[package]
name = "runtime"
version = "0.1.0-alpha"
edition = "2018"

[dependencies]
rust-crypto = { name = "crypto", version = "0.2.36" }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"

dirs = { path = "../dirs" }
