name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install llvm
        run: sudo apt-get install llvm

      - name: Login
        run: echo ${{ secrets.CRATES_IO_TOKEN }} | cargo login

      - name: Publish
        run: |
          # smoelius: The crates must be published in this order, which is a reverse topological
          # sort of `doc/crates.dot`.
          for X in dirs runtime macro . cargo-test-fuzz; do
            # smoelius: Continue in case of a previous failed publish attempt.
            cargo publish --manifest-path "$X"/Cargo.toml || true
            # smoelius: Give `crate.io` a chance to update.
            sleep 1m
          done

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'rc') }}
